application/videos/models.py
from application import db

class Video(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    title = db.Column(db.String(144), nullable=False)
    url = db.Column(db.String(144), nullable=False)
    creator = db.Column(db.String(144), nullable=False)
    description = db.Column(db.String(200), nullable=False)
    platform = db.Column(db.String(144), nullable=False)

    def __init__(self, title, url, creator, description, platform):
        self.title = title
        self.url = url
        self.title = title
        self.creator = creator
        self.platform = platform
        self.description = description

application/videos/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, validators


class VideoForm(FlaskForm):
    url = StringField("Video URL", [validators.DataRequired(), validators.Length(min=2)])

    class Meta:
        csrf = False

application/__init__.py
import os
import click
from flask import Flask
from flask.cli import with_appcontext
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def create_app(test_config=None):

    app = Flask(__name__, instance_relative_config=True)

    db_url = os.environ.get("DATABASE_URL")

    if db_url is None:
        db_url = "sqlite:///" + \
            os.path.join(app.instance_path, "application.sqlite")
        os.makedirs(app.instance_path, exist_ok=True)

    app.config.from_mapping(
        SECRET_KEY=os.environ.get("SECRET_KEY", "dev"),
        SQLALCHEMY_DATABASE_URI=db_url,
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
    )

    if test_config is None:
        app.config.from_pyfile("config.py", silent=True)
    else:
        app.config.update(test_config)

    db.init_app(app)
    app.cli.add_command(init_db_command)

    # apply the blueprints to the app
    from application import videos

    app.register_blueprint(videos.bp)

    app.add_url_rule("/", endpoint="index")

    return app


def init_db():
    from application.videos.models import Video

    db.drop_all()
    db.create_all()
    initial_video = Video("Iha ok mut ootko kattonu simpsonit sarjasta jakson himo läski homer", "QyYyuTsx9lE", "Goolag User",
                          "iha ok mut ootko kattonu simpsonit sarjasta jakson himo läski homer :D siinä esiintyy koko simpsonit perhe",
                          "youtube")
    initial_stream = Video("DreamHackCS",
                           "https://www.twitch.tv/dreamhackcs",
                           "DreamHackCS","DreamHack's Counter-Strike: Global Offensive channel.",
                           "twitch")

    db.session().add(initial_video)
    db.session().add(initial_stream)
    db.session().commit()


def init_test_db():
    db.drop_all()
    db.create_all()


@click.command("init-db")
@with_appcontext
def init_db_command():
    """Clear existing data and create new tables."""
    init_db()
    click.echo("Initialized the database.")


app = create_app()

application/videos/views.py
from dotenv import load_dotenv
import googleapiclient.discovery
import os
from application.videos.forms import VideoForm
from application.videos.models import Video
from application import db
import re
import json
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
import flask
import twitch

load_dotenv()
DEVELOPER_KEY = os.getenv("API_KEY")
if os.environ.get("HEROKU", 2) == 1:
    DEVELOPER_KEY = os.environ.get("API_KEY")

if os.environ.get("CIRCLECI", 2) == 1:
    DEVELOPER_KEY = os.environ.get("API_KEY")

bp = Blueprint("videos", __name__)

if os.environ.get("HEROKU", 2) == 1:
    TWITCH_API_KEY = os.environ.get("TWITCH_API_KEY")
else:
    TWITCH_API_KEY = os.getenv("TWITCH_API_KEY")

helix = twitch.Helix(TWITCH_API_KEY)


@bp.route("/videos/new/")
def video_form():
    form = VideoForm()
    return render_template("videos/new.html", form=form)


@bp.route("/videos/", methods=["POST"])
def videos_create():

    if flask.request.method != 'POST':
        return

    form = VideoForm(request.form)

    if not form.validate_on_submit():
        return render_template("videos/new.html", form=form)

    if "youtu" in form.url.data:
        try:
            api_service_name = "youtube"
            api_version = "v3"

            youtube = googleapiclient.discovery.build(
                api_service_name, api_version, developerKey=DEVELOPER_KEY)

            if "?v=" in form.url.data:
                video_id = re.search(
                    r'(?<=\?v=).{11}', form.url.data)[0]
            else:
                video_id = re.search(
                    r'(?<=\.be\/).{11}', form.url.data)[0]

            res = youtube.videos().list(
                part="snippet",
                id=video_id
            )
            response = res.execute()
            data = response["items"][0]

            url = data["id"]
            title = data["snippet"]["title"]
            description = data["snippet"]["description"][:150]
            creator = data["snippet"]["channelTitle"]
            platform = "youtube"
            new_video = Video(title, url, creator,
                              description, platform)
            db.session().add(new_video)
            db.session.commit()

            return redirect(url_for("videos.videos_index"))
        except:
            form.url.errors = [
                f"Wrong url, url must be typed like 'https://www.youtube.com/watch?v=StqIbgNA35s'"]
            return render_template("videos/new.html", form=form)
    if "twitch" in form.url.data:
        try:
            url = form.url.data
            name = re.search(r'(?<=.tv\/).*', url)[0]
            user = helix.user(name)
            title = user.display_name
            description = user.description
            creator = title
            platform = "twitch"
            new_video = Video(title, url, creator,
                              description, platform)
            db.session().add(new_video)
            db.session.commit()
            return redirect(url_for("videos.videos_index"))
        except:
            form.url.errors = [
                f"Invalid url"]
            return render_template("videos/new.html", form=form)



@bp.route("/videos/remove/<video_id>", methods=["POST"])
def remove_video(video_id):
    video = Video.query.get(video_id)
    db.session().delete(video)
    db.session().commit()

    return redirect(url_for("videos.videos_index"))


@bp.route("/videos", methods=["GET"])
def videos_index():
    return render_template("videos/list.html", videos=Video.query.all())


@bp.route('/')
def index():
    return render_template("index.html")

application/templates/frontpage.html
{% extends "layout.html" %}

{% block body %}
  <p>
    Hello world!
  </p>
{% endblock %}

application/templates/index.html
{% extends "layout.html" %} {% block body %}
<p>
  Welcome to Konsulttitukka Consulting Oy's video bookmarking app! Here you can browse Youtube/Twitch bookmarks or add your own bookmarks.
</p>
{% endblock %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Video bookmarks</title>

  <!-- Bootstrap core CSS -->
  <!-- <link href="../static/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

  <!-- Custom styles for this template -->
  <!-- <link href="../static/css/simple-sidebar.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/simple-sidebar.css') }}">

  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <script>
        function hideBlock(id) {
            var block = document.getElementById(id);

            if(block.style.display === "none"){
                block.style.display = "block";
            } else {
                block.style.display = "none";
            }
        }
    </script>




</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">
        <a class="navbar-brand" href="{{ url_for('videos.index') }}">Video bookmarks</a>
      </div>


      <div class="list-group list-group-flush">

        <a href="{{ url_for('videos.videos_index') }}" name="all videos"
          class="list-group-item list-group-item-action bg-light">See all</a>

        <a href="{{ url_for ('videos.video_form') }}" name="add video" class="list-group-item list-group-item-action bg-light">Add a
          video</a>

      </div>
    </div>
    <!-- /#sidebar-wrapper -->


    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/uberballo/OT-miniprojekti">Github</a>
            </li>

          </ul>
        </div>
      </nav>
      <main role="main" class="container">
        {% block body %}
        <p>kkontent</p>
        {% endblock %}
      </main>

    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function (e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>


</body>

</html>

application/templates/videos/list.html
{% extends "layout.html" %} {% block body %}
<!-- table table-hover table-sm  -->
<h1 class="text-center">Video bookmarks</h1>


<script type="text/javascript">
  const hideOnClick = (videoId) => {
    let video = document.getElementById(videoId)
    console.log(video.style.display)
    video.style.display === "none" ? video.style.display = "block" : video.style.display = "none"
  }
</script>

{% for video in videos %}
<div id="{{ video.title }}">


  <div class="card mb-3">
    <div class="card-body">

      <h5 class="card-title">{{ video.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ video.description}} ...</h6>
      <button class="btn btn-warning" onclick="hideOnClick('{{video.id}}')">Hide</button>

      <div id="{{video.id}}" style="display: none;">
        {% if video.platform == "youtube"%}

        <div class="embed-responsive embed-responsive-1by1">
          <iframe width="420" height="315" src="https://www.youtube.com/embed/{{ video.url }}">
          </iframe>
        </div>


        {% elif video.platform == "twitch" %}

        <div class="embed-responsive embed-responsive-1by1">
          <div id="twitch-embed-{{video.id}}"></div>
          <script src="https://player.twitch.tv/js/embed/v1.js"></script>
          <script type="text/javascript">
            var embed = new Twitch.Player("twitch-embed-{{video.id}}", {
              width: 854,
              height: 480,
              channel: "{{video.creator}}",
              layout: "video",
              autoplay: false
            });
          </script>

        </div>
        {% endif %}
      </div>
      <form method="POST" action="{{ url_for('videos.remove_video', video_id=video.id) }}">
        <input class="btn btn-danger" type="submit" name="view" value="remove video" />
      </form>
    </div>
  </div>
</div>



{% endfor %} {% endblock %}

application/templates/videos/new.html
{% extends "layout.html" %}

{% block body %}
<h1 class="text-center">Add a new bookmark</h1>
<form method="POST" action="{{ url_for('videos.videos_create') }}">
  <div class="form-group">
    {{ form.url.label }}
    {{ form.url(class="form-control") }}
    <td>
      <ul>
        {% for error in form.url.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </td>
  </div>
  <input type="submit" name="addButton" class="btn btn-success my-2 my-sm-0" value="Add a new video" />
  </div>
</form>
{% endblock %}

application/templates/videos/update.html
{% extends "layout.html" %}

{% block body %}
<h1 class="text-center">Updating video</h1>
<form method="POST" action="{{ url_for('videos.videos_update', video_id=video.id) }}">
  <div class="form-group">
    {{ form.title.label }}
    {{ form.title(class="form-control")}}
    <td>
      <ul>
        {% for error in form.title.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </td>
  </div>
  <div class="form-group">
    {{ form.url.label }}
    {{ form.url(class="form-control")}}
    <ul>
      {% for error in form.url.errors %}
      <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
  <div>
    <input class="btn btn-primary" type="submit" value="Update data" />
  </div>
</form>
{% endblock %}

application/templates/videos/video.html
{% extends "layout.html" %}

{% block body %}

<h1 class="text-center">{{video.title}}</h2>
  <div class="jumbotron">
    <div class="container">
        <div class="text-center">{{video.url}}</div>
    </div>
  </div>
  <div>
    <form method="POST" action="{{ url_for('videos.videos_update', video_id=video.id) }}">
      <input class="btn btn-primary" type="submit" name="update" value="Update video" />
    </form>
  </div> 

{% endblock %}